# Generated by Django 3.1.2 on 2020-10-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/copies'),
        ),
    ]
