# Generated by Django 3.1.2 on 2020-10-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201027_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='photo',
            field=models.ImageField(blank=True, upload_to='copies'),
        ),
    ]
