# Generated by Django 3.1.2 on 2020-10-27 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201027_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
